### ISSUE TITLE
Бага с апдейтами

### ISSUE THREAD

**Issue by Fi1osof** [ilyautkin/autoRedirector#4]
Илья, привет!

Глянь комменты здесь: http://modxclub.ru/topics/problema-s-shopmodxbox-1516.html#comment-5198
И вот этот багфикс глянь: https://github.com/Fi1osof/modRedirect/commit/0f07590448a2be47b3dfe721cb733da079ae442f#diff-25ac3838aff8b1b659ee3b75bccadce8R48

**Comment by ilyautkin** [comment]
Исправлено https://github.com/ilyautkin/autoRedirector/commit/e72620cb6e1abf494bb781b135d724abf935e685

**Comment by Fi1osof** [comment]
Не за что!
