### ISSUE TITLE
Оптимизация

### ISSUE THREAD

**Issue by sergant210** [ilyautkin/autoRedirector#5]
Предложение по небольшой оптимизации - кэшировать массив с настройками (ключи - это uri, а значения - это id ресурса). После изменения URI ресурса в админке создавать/пересоздавать кэш. А в onPageNotFound загружать массив из кэша и редиректить `$modx->sendRedirect($array[$uri],'ResponseCode...');`
Тогда не нужно загружать модель и делать запрос в БД при загрузке страницы сайта.

**Comment by ilyautkin** [comment]
Ну модель загружается и запрос в БД идет только во время событий **OnResourceSort** и **OnPageNotFound**, поэтому сильного ускорение кеширование не даст. Тем более, что ресурсов на сайте может быть очень много, хранить такой большой массив в файле нелогично - его долго будет генерировать, в нём неудобно искать. Так что я не думаю, что в этом есть смысл...

**Comment by sergant210** [comment]
> Тем более, что ресурсов на сайте может быть очень много

Думаешь? Т.е. народ постоянно меняет uri?

> хранить такой большой массив в файле нелогично - его долго будет генерировать, в нём неудобно искать.

Не думаю, что он будет большой. А во-вторых, генерируется он в админке, где скорость не так критична, как на сайте.

> Так что я не думаю, что в этом есть смысл..

У меня на сайте теги и похожие статьи так сделаны. Скорость увеличилась заметно. А сайт-то маленький. :)
Я не навязываю свое мнение. Это просто предложение.
