### ISSUE TITLE
Добавить правило через API MODX

### ISSUE THREAD

**Issue by Skippidar** [ilyautkin/autoRedirector#7]
Каким образом можно добавить правило не в админ панели, а, к примеру, в сниппете? Хочу разрешить использование вложенных url, но для начала необходимо сохранить предыдущие ссылки. 
Вот хотелось бы узнать как это можно сделать.

**Comment by ilyautkin** [comment]
Вот, например, код для импорта правил из CSV: https://ilyaut.ru/cribs-for-modx/import-rules-from-csv-autoredirector/

**Comment by Skippidar** [comment]
Благодарю, то что нужно.
